version: '3'

services:
  devices_db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'devices_db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3308:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      demo_net:
        ipv4_address: 172.30.1.3
  device_microservice:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8082:8081"
    environment:
      - DB_IP=devices_db
      - DB_PORT=3306
      - DB_DBNAME=devices_db
      - DB_USER=root
      - DB_PASSWORD=password
    networks:
      demo_net:
        ipv4_address: 172.30.1.2

volumes:
  my-db:

networks:
  demo_net:
    external: true
