version: '3'

services:
  users_db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'users_db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    volumes:
      - my_db:/var/lib/mysql
    networks:
      demo_net:
        ipv4_address: 172.30.0.3
  user_microservice:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DB_IP=users_db
      - DB_PORT=3306
      - DB_DBNAME=users_db
      - DB_USER=root
      - DB_PASSWORD=password
    networks:
      demo_net:
        ipv4_address: 172.30.0.2

volumes:
  my_db:

networks:
  demo_net:
    external: true