version: '3'

services:
  device_microservice:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8084:8083"
    networks:
      demo_net:
        ipv4_address: 172.30.3.2

networks:
  demo_net:
    external: true
