version: '3'

services:

  react:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
       - "3003:3000"
    environment:
      - BACKENDUSERS=172.30.0.2
      - BACKENDDEVICES=172.30.1.2
    networks:
      demo_net:
        ipv4_address: 172.30.0.10

networks:
  demo_net:
    external: true
